dogomugs/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path
from django.urls.conf import include

from accounts import urls as account_urls
from basket import urls as basket_urls
from checkout import urls as checkout_urls
from contact import urls as contact_urls
from home import urls as home_urls
from orders import urls as orders_urls
from products import urls as product_urls

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include(home_urls)),
    path("accounts/", include(account_urls)),
    path("products/", include(product_urls)),
    path("basket/", include(basket_urls)),
    path("checkout/", include(checkout_urls)),
    path("contact/", include(contact_urls)),
    path("orders/", include(orders_urls)),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/urls.py
from django.urls import path

from home.views import HomeView

urlpatterns = [
    path("", HomeView.as_view(), name="home")
]

orders/urls.py
from django.urls import path

from orders.views import OrderDetailsDetailView, OrderDetailsListView

urlpatterns = [
    path("", OrderDetailsListView.as_view(), name="order-list"),
    path("<int:pk>/", OrderDetailsDetailView.as_view(), name="order-detail"),
]

checkout/models.py
from django.contrib.auth.models import User
from django.db import models

from products.models import Product


class ShippingAddress(models.Model):
    """Model for ShippingAddress."""
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    full_name = models.CharField(max_length=100, null=False, blank=False)
    primary_address = models.CharField(max_length=50, null=False, blank=False)
    secondary_address = models.CharField(
        max_length=50, null=False, blank=False)
    town_or_city = models.CharField(max_length=100, null=False, blank=False)
    county = models.CharField(max_length=100, null=False, blank=False)
    postcode = models.CharField(max_length=10, null=False, blank=False)
    country = models.CharField(max_length=50, null=False, blank=False)
    phone_number = models.CharField(max_length=20, null=False, blank=False)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        """String representation for ShippingAddress."""
        return f"{self.id}: {self.full_name} - {self.primary_address}"

    class Meta:
        verbose_name_plural = "Shipping Addresses"


class OrderDetails(models.Model):
    """Model for OrderDetails."""
    user = models.ForeignKey(
        User, blank=False, null=True, on_delete=models.SET_NULL)
    shipping_address = models.ForeignKey(
        ShippingAddress, blank=False, null=True, on_delete=models.SET_NULL)
    total_price = models.DecimalField(
        decimal_places=2, max_digits=8, default=0)
    items_quantity = models.IntegerField(null=False, blank=False, default=0)
    payment_confirmed = models.BooleanField(default=False)
    stripe_id = models.CharField(max_length=100)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        """String representation for OrderDetails."""
        return f"{self.id}: {self.user.username}: {self.total_price}"

    class Meta:
        """Meta attributes, defining the plural representation."""
        verbose_name_plural = "Orders Details"


class OrderItems(models.Model):
    """Model for OrderItems."""
    product = models.ForeignKey(Product, on_delete=models.PROTECT)
    order_details = models.ForeignKey(OrderDetails, on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField()
    price = models.DecimalField(decimal_places=2, max_digits=5)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        """String representation for OrderItems."""
        return f"{self.id}: {self.quantity} - {self.product.name}"

    class Meta:
        """Meta attributes, defining the plural representation."""
        verbose_name_plural = "Orders Items"

orders/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import detail, list

from checkout.models import OrderDetails


class OrderDetailsListView(LoginRequiredMixin, list.ListView):
    """Render a list of OrderDetails objects.

    Provide functionality for pagination and searching of OrderDetails in a list view.
    """

    model = OrderDetails
    paginate_by = 6
    template_name = "order_list.html"

    def get_queryset(self):
        """Override get_queryset to enable search OrderDetails filtering."""
        queryset = super().get_queryset()
        queryset = queryset.filter(
            user=self.request.user, items_quantity__gt=0).order_by("-updated")
        return queryset


class OrderDetailsDetailView(LoginRequiredMixin, detail.DetailView):
    """Render a detail view of the OrderDetails model instance."""

    model = OrderDetails
    template_name = "order_detail.html"

    def get_queryset(self):
        """Override get_queryset to scope queryset to user."""
        queryset = super().get_queryset()
        return queryset.filter(user=self.request.user)

orders/templates/order_detail.html
{% extends "base.html" %}
{% block content %}
{% load static %}
<div class="card mb-3 container justify-content-center">
    <div class="row">
        <div class="d-none d-md-block col-md-6">
            <img src="{% static 'img/corgi.jpg' %}" class="rounded-start form-image" alt="Corgi">
        </div>
        <div class="col-12 col-md-6">
            <div id="order-detail-card" class="card-body">
                <h4 class="card-title my-5">Ordered on {{orderdetails.created}}</h4>
                <p>{{orderdetails.items_quantity}} items in total</p>
                <p>Total price: £{{orderdetails.total_price}}</p>
                <ul class="list-group list-group-flush">
                    {% for order_item in orderdetails.orderitems_set.all %}
                    <li class="list-unstyled">{{ order_item.quantity }} X {{ order_item.product.name }}</li>
                    <li class="list-unstyled">£{{ order_item.price }} each</li>
                </ul>
                {% endfor %}
                <h5 class="mt-5">Shipping Address:</h5>
                <ul class="list-group list-group-flush">
                    <li class="list-unstyled">{{orderdetails.shipping_address.full_name}}</li>
                    <li class="list-unstyled">{{orderdetails.shipping_address.primary_address}}</li>
                    <li class="list-unstyled">{{orderdetails.shipping_address.secondary_address}}</li>
                    <li class="list-unstyled">{{orderdetails.shipping_address.town_or_city}}</li>
                    <li class="list-unstyled">{{orderdetails.shipping_address.county}}</li>
                    <li class="list-unstyled">{{orderdetails.shipping_address.postcode}}</li>
                    <li class="list-unstyled">{{orderdetails.shipping_address.country}}</li>
                    <li class="list-unstyled">{{orderdetails.shipping_address.phone_number}}</li>
                </ul>
            </div>
        </div>
        {% if not orderdetails.payment_confirmed %}
        <p class="my-3 d-flex justify-content-center"><a href="{% url 'payment' order_id=orderdetails.id %}" class="btn btn-primary text-uppercase">Continue payment</a></p>
            {% endif %}
        <p class="my-3 d-flex justify-content-center"><a href="{% url 'order-list' %}" class="btn btn-primary text-uppercase">Back to all orders</a></p>
    </div>
</div>
{% endblock %}

orders/templates/order_list.html
{% extends "base.html" %}
{% block content %}
{% if object_list|length > 0 %}
<div class="container my-4 justify-content-center">
  <h2 class="text-uppercase">My orders</h2>
</div>
<div class="container">
  <div class="row">
    {% for order in object_list %}
    <div class="col-xs-12 col-sm-6 col-md-4 d-flex justify-content-center my-1">
      <div class="card my-3">
        <div class="card-body">
          <h5 class="card-title">{{order.created}}</h5>
            <ul class="list-group list-group-flush">
              <li class="list-group-item">£{{order.total_price}}</li>
                {% if order.items_quantity > 1 %}
                <li class="list-group-item">{{order.items_quantity}} items</li>
                {% else %}
                <li class="list-group-item">{{order.items_quantity}} item</li>
                {% endif %}
                {% if order.payment_confirmed %}
                <li class="list-group-item">Payment status <i class="fa-solid fa-check" aria-hidden="true" title="Payment complete"></i></li>
                {% else %}
                <li class="list-group-item">Payment status <i class="fa-solid fa-x" aria-hidden="true" title="Pending payment"></i></li>
                {% endif %}
                <li class="list-group-item"><a href="{% url 'order-detail' pk=order.id %}" class="btn btn-primary text-uppercase mt-3">Order details</a></li>
              </ul>
        </div>
      </div>
    </div>
    {% endfor %}
    {% include "layout/pagination_control.html" %}
    {% else %}
    <div class="container">
      <p class="text-uppercase mt-4 justify-content-center d-flex">There are no orders to display!</p>
      <a href="{% url 'product-list' %}" class="text-uppercase mt-5 justify-content-center d-flex text-decoration-none contact-us">Shop now!</a>
    </div>
    {% endif %}
  </div>
</div>
{% endblock %}